### ISSUE TITLE
Pre-cropping Photostream image crashes app

### ISSUE THREAD

**Issue by cohoe** [jocosocial/tricordarr#223]
After adding:
```
cropping: true,
width: 2048,
height: 2048,
```

to the ImagePicker options.

**Comment by cohoe** [comment]
`adb logcat --pid ${pid}`

```
12-05 20:11:40.477  6323  6543 D PipelineManager: OCR process succeeded via visionkit pipeline.
12-05 20:11:40.480  6323  6323 D ImageTextBlurModule: Text detected in image.
12-05 20:11:40.482  6323  6323 D AndroidRuntime: Shutting down VM
12-05 20:11:40.483  6323  6422 D TransportRuntime.SQLiteEventStore: Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
--------- beginning of crash
12-05 20:11:40.484  6323  6323 E AndroidRuntime: FATAL EXCEPTION: main
12-05 20:11:40.484  6323  6323 E AndroidRuntime: Process: com.tricordarr, PID: 6323
12-05 20:11:40.484  6323  6323 E AndroidRuntime: java.lang.IllegalStateException: Immutable bitmap passed to Canvas constructor
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at android.graphics.Canvas.<init>(Canvas.java:114)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at com.tricordarr.ImageTextBlurModule$blurTextInImage$1.invoke(ImageTextBlur.kt:66)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at com.tricordarr.ImageTextBlurModule$blurTextInImage$1.invoke(ImageTextBlur.kt:41)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at com.tricordarr.ImageTextBlurModule.blurTextInImage$lambda$0(ImageTextBlur.kt:41)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at com.tricordarr.ImageTextBlurModule.$r8$lambda$PWfhDU_wNIYVyOODzWjKa6UzbMQ(Unknown Source:0)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at com.tricordarr.ImageTextBlurModule$$ExternalSyntheticLambda0.onSuccess(Unknown Source:2)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8177)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
12-05 20:11:40.484  6323  6323 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
12-05 20:11:40.486  6323  6422 D TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
```
